### ISSUE TITLE
Make keys for actions in modbot be remappable

### ISSUE THREAD

**Issue by Goorakh** [X606/ModBot#9]
Add a way to add a fakeAction to the list of keys in normal game, so it can be changed from the same place as the normal key remapping. Maybe a separate "Modded Keys" tab?

**Comment by X606** [comment]
This could probably be done in a better way, like being able to send a API request that gets the keycode instead of a fakeAction

**Comment by X606** [comment]
This could be made a part of the new modded settings window

**Comment by X606** [comment]
Most of the code work for this is now done in the experimental branch, just need to create the assets for the UI of it

**Comment by X606** [comment]
This is done in the experimental branch except for the fact that it doesn't work when in the game for some reason, will look into it later

**Comment by X606** [comment]
This should be done working with the new modded settings.

**Comment by Goorakh** [comment]
This is not done, we currently only support mods adding rebindable keys, the binds in Mod-Bot (like, opening/closing the console) are currently not remappable

**Comment by X606** [comment]
This feature is added to mod-bot 2.0

**Comment by X606** [comment]
From mod-bot 2.0 forward, this feature will be added for mod-bot keys too
